(()=>{
const REDIRECT='https://wtm-whats-the-move.vercel.app/fever-callback.html';
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(48)),verifier=b64(bytes),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return{verifier,challenge:b64(digest)}}
async function connect(){const btn=document.querySelector('#connectFever'),status=document.querySelector('#feverStatus');if(btn)btn.disabled=true;if(status)status.textContent='Preparing Fever authorization…';try{const reg=await fetch('https://toolbox-nine-eta.vercel.app/api/wtm-fever-register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({redirect_uri:REDIRECT})}),d=await reg.json();if(!reg.ok)throw Error(d.error||'Fever registration failed');const {verifier,challenge}=await pkce(),state=b64(crypto.getRandomValues(new Uint8Array(24)));localStorage.setItem('wtm-fever-oauth',JSON.stringify({client_id:d.client_id,client_secret:d.client_secret,code_verifier:verifier,state,redirect_uri:REDIRECT}));const u=new URL(d.authorization_endpoint);u.searchParams.set('response_type','code');u.searchParams.set('client_id',d.client_id);u.searchParams.set('redirect_uri',REDIRECT);u.searchParams.set('scope','openid');u.searchParams.set('state',state);u.searchParams.set('code_challenge',challenge);u.searchParams.set('code_challenge_method','S256');location.href=u.toString()}catch(e){if(status)status.textContent=e.message;if(btn)btn.disabled=false}}
function tokenData(){try{return JSON.parse(localStorage.getItem('wtm-fever-token')||'null')}catch{return null}}
async function validToken(){let t=tokenData();if(!t)return null;const expires=(t.obtained_at||0)+(Number(t.expires_in||3600)*1000);if(Date.now()<expires-120000)return t.access_token;if(!t.refresh_token)return null;try{const r=await fetch('https://toolbox-nine-eta.vercel.app/api/wtm-fever-token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:t.client_id,client_secret:t.client_secret,refresh_token:t.refresh_token})}),d=await r.json();if(!r.ok)throw Error();t={...t,...d,refresh_token:d.refresh_token||t.refresh_token,obtained_at:Date.now()};localStorage.setItem('wtm-fever-token',JSON.stringify(t));return t.access_token}catch{return null}}
async function syncFever(show=false){const token=await validToken();if(!token)return;const status=document.querySelector('#feverStatus');if(show&&status)status.textContent='Syncing Fever Houston catalog…';try{const r=await fetch('https://toolbox-nine-eta.vercel.app/api/wtm-fever-events',{headers:{authorization:'Bearer '+token},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Fever sync failed');if(d.events?.length)events=dedupe([...(d.events||[]),...events]);const s={source:'Fever',url:'https://feverup.com/en/houston',mode:'official OAuth feed',status:'live',count:d.count||0};statuses=[s,...statuses.filter(x=>x.source!=='Fever')];if(typeof updateSelects==='function')updateSelects();render();if(status)status.textContent=`Connected · ${d.count||0} Fever events syncing automatically`;const sync=document.querySelector('#sync');if(sync)sync.textContent=`${events.length} events across connected WTM sources`}catch(e){if(status)status.textContent='Fever connected, but this sync failed. Tap Retry.'}}
document.addEventListener('click',e=>{const id=e.target?.id;if(id==='connectFever'){e.preventDefault();connect()}if(id==='syncFever'){e.preventDefault();syncFever(true)}if(id==='disconnectFever'){e.preventDefault();localStorage.removeItem('wtm-fever-token');localStorage.removeItem('wtm-fever-oauth');location.reload()}});
setTimeout(()=>syncFever(false),1500);
if(new URLSearchParams(location.search).has('fever_connected'))setTimeout(()=>syncFever(true),400);
window.WTMFever={connect,sync:syncFever};
})();