(()=>{
const baseMatches=matches,baseDiscover=discover;
function semanticPass(e,q){q=(q||'').trim().toLowerCase();if(!q)return true;const blob=textBlob(e);const t=tags(e);if(/\bsolo\b/.test(q)&&solo(e)<9)return false;if(/\b(sport|sports|sporting|game|games)\b/.test(q)&&!t.includes('Sports'))return false;if(/\b(concert|concerts|music|live music|show|shows)\b/.test(q)&&!t.includes('Music'))return false;if(/\b(comedy|comedian|standup|stand-up)\b/.test(q)&&!t.includes('Comedy'))return false;if(/\b(food|drink|drinks|wine|brunch|dinner|cocktail)\b/.test(q)&&!t.includes('Food + Wine'))return false;if(/\b(art|artsy|creative|museum|gallery)\b/.test(q)&&!t.includes('Artsy'))return false;if(/\b(outdoor|outdoors|park|festival|beach)\b/.test(q)&&!t.includes('Outdoors'))return false;const stop=new Set(['a','an','the','event','events','thing','things','something','somewhere','solo','sport','sports','sporting','game','games','concert','concerts','music','live','show','shows','comedy','comedian','standup','stand-up','food','drink','drinks','wine','brunch','dinner','cocktail','art','artsy','creative','museum','gallery','outdoor','outdoors','park','festival','beach','near','nearby','me','for','to','go','going']);const words=q.replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>1&&!stop.has(w));return words.every(w=>blob.includes(w)||blob.includes(w.replace(/s$/,'')))}
matches=function(e){const q=document.querySelector('#search')?.value||'';const input=document.querySelector('#search');let pass=true;if(input){const original=input.value;input.value='';pass=baseMatches(e);input.value=original}if(!pass)return false;if(quick==='sports'&&!tags(e).includes('Sports'))return false;return semanticPass(e,q)};
discover=function(){let html=baseDiscover();const list=visible().slice().sort((a,b)=>new Date(a.date)-new Date(b.date));const sports=list.filter(e=>tags(e).includes('Sports'));if(sports.length)html+=row('Sports & games','Texans, Rockets, Astros, Dynamo and major sporting events',sports);return html};
function addSportsChip(){const chips=document.querySelector('#chips');if(chips&&!chips.querySelector('[data-filter="sports"]')){const b=document.createElement('button');b.dataset.filter='sports';b.textContent='Sports';const music=chips.querySelector('[data-filter="music"]');chips.insertBefore(b,music||null);b.addEventListener('click',()=>{quick='sports';chips.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()})}}
let lockedY=0;function lockBody(){if(document.body.classList.contains('wtm-modal-open'))return;lockedY=window.scrollY;document.body.classList.add('wtm-modal-open');document.body.style.top=`-${lockedY}px`}function unlockBody(){if(!document.body.classList.contains('wtm-modal-open'))return;document.body.classList.remove('wtm-modal-open');document.body.style.top='';window.scrollTo(0,lockedY)}
function syncModalLock(){const m=document.querySelector('#modal');if(!m)return;if(m.classList.contains('hide'))unlockBody();else{lockBody();const card=m.querySelector('.modalCard');if(card){card.scrollTop=0;card.addEventListener('touchmove',e=>e.stopPropagation(),{passive:true})}}}
const modal=document.querySelector('#modal');if(modal)new MutationObserver(syncModalLock).observe(modal,{attributes:true,attributeFilter:['class'],childList:true,subtree:false});
const oldRender=render;render=function(){oldRender();addSportsChip();syncModalLock()};
addSportsChip();syncModalLock();
})();