(()=>{
const PROVIDERS=[
 ['POSH','https://posh.vip/explore/houston'],['Bucket Listers','https://bucketlisters.com/experience/houston'],['Fever','https://feverup.com/en/houston'],['DICE','https://dice.fm/browse/houston'],['Do713','https://do713.com/events'],['Houstonia','https://www.houstoniamag.com/arts-and-culture'],['Discovery Green','https://www.discoverygreen.com/events/'],['POST Houston','https://www.posthtx.com/event'],['Gametime','https://gametime.co/houston-tickets/metros/hou'],['Total Wine','https://www.totalwine.com/events'],['Ticketmaster','https://www.ticketmaster.com/discover/houston'],['Live Nation','https://www.livenation.com/discover/concerts/houston'],['AXS','https://www.axs.com/search?q=Houston'],['NRG Park','https://www.nrgpark.com/events-tickets/'],['Toyota Center','https://www.toyotacenter.com/events/all'],['713 Music Hall','https://www.713musichall.com/shows'],['Smart Financial Centre','https://www.smartfinancialcentre.net/events'],['Cynthia Woods Pavilion','https://www.woodlandscenter.org/events'],['Houston Rockets','https://www.nba.com/rockets/schedule?Location=Home'],['Houston Astros','https://www.mlb.com/astros/schedule'],['Houston Texans','https://www.houstontexans.com/schedule/'],['Houston Dynamo','https://www.houstondynamofc.com/schedule/']
];
let gps=(()=>{try{return JSON.parse(localStorage.getItem('wtm-gps')||'null')}catch{return null}})();
const oldMiles=miles;
function haversine(a,b,c,d){const R=3958.8,toR=x=>x*Math.PI/180,dp=toR(c-a),dl=toR(d-b),q=Math.sin(dp/2)**2+Math.cos(toR(a))*Math.cos(toR(c))*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
miles=function(e){if(gps&&Number.isFinite(Number(e.lat))&&Number.isFinite(Number(e.lng)))return Math.round(haversine(gps.lat,gps.lng,Number(e.lat),Number(e.lng))*10)/10;return oldMiles(e)};
function updateGpsButton(){const b=document.querySelector('#locationBtn');if(!b)return;b.textContent=gps?'⌖ GPS on':'⌖ Use my location';b.title=gps?'Using your device location for event distance':'Use GPS for more accurate distance'}
function useGps(){if(!navigator.geolocation){toast('GPS is not supported in this browser');return}const b=document.querySelector('#locationBtn');if(b)b.textContent='⌖ Locating…';navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,updatedAt:Date.now()};localStorage.setItem('wtm-gps',JSON.stringify(gps));updateGpsButton();render();toast(`GPS enabled · accuracy about ${Math.round(p.coords.accuracy)} m`)},e=>{updateGpsButton();toast(e.code===1?'Location permission was not granted':'Could not get your location')},{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}
function customModal(){const m=document.querySelector('#modal');m.classList.remove('hide');m.innerHTML=`<div class="modalCard"><div class="detailBody"><div class="sheetHead"><div><span class="kicker">ADD YOUR OWN PLAN</span><h2>Add an event</h2></div><button class="close" id="customClose">×</button></div><p>Create anything from a private party or dinner reservation to an invite-only event. It will go straight into Nikki’s Social Calendar.</p><form id="customEventForm" class="quickAdd"><div class="customGrid"><label>Event name<input required id="ceTitle" placeholder="Birthday dinner"></label><label>Date & time<input required id="ceDate" type="datetime-local"></label><label>End time<input id="ceEnd" type="datetime-local"></label><label>Venue<input id="ceVenue" placeholder="Restaurant, house, venue..."></label><label>Address<input id="ceAddress" placeholder="Street address"></label><label>ZIP<input id="ceZip" inputmode="numeric" placeholder="77002"></label><label>Area<input id="ceArea" placeholder="Montrose, Katy, Galveston..."></label><label>Cost<input id="cePrice" type="number" min="0" step="0.01" placeholder="0"></label><label>Flyer / image URL<input id="ceImage" type="url" placeholder="https://..."></label><label>Event link<input id="ceUrl" type="url" placeholder="https://..."></label></div><label>Notes<textarea id="ceNotes" rows="4" placeholder="Dress code, reservation name, parking, who is coming..."></textarea></label><div class="sheetActions"><button type="button" class="ghost" id="customCancel">Cancel</button><button class="primary" type="submit">Add to Social Calendar</button></div></form></div></div>`;
 const close=()=>{m.classList.add('hide');m.innerHTML=''};document.querySelector('#customClose').onclick=close;document.querySelector('#customCancel').onclick=close;document.querySelector('#customEventForm').onsubmit=e=>{e.preventDefault();const date=document.querySelector('#ceDate').value;if(!date)return;const id='custom:'+Date.now();const ev={id,title:document.querySelector('#ceTitle').value.trim(),source:'My Event',date:new Date(date).toISOString(),endDate:document.querySelector('#ceEnd').value?new Date(document.querySelector('#ceEnd').value).toISOString():null,area:document.querySelector('#ceArea').value.trim()||'Greater Houston',venue:document.querySelector('#ceVenue').value.trim()||'Private plan',address:document.querySelector('#ceAddress').value.trim(),zip:document.querySelector('#ceZip').value.trim(),price:document.querySelector('#cePrice').value===''?null:Number(document.querySelector('#cePrice').value),url:document.querySelector('#ceUrl').value.trim(),description:document.querySelector('#ceNotes').value.trim(),image:document.querySelector('#ceImage').value.trim(),lat:null,lng:null,sourceMode:'manual'};imported.push(ev);events=dedupe([ev,...events]);if(!plans.includes(id))plans.push(id);store('wtm-imported-events',imported);store('wtm-plans',plans);close();tab='calendar';document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='calendar'));render();toast('Added to Nikki’s Social Calendar')}
}
function clipboardImport(){if(!navigator.clipboard?.readText){toast('Clipboard access is unavailable here');return}navigator.clipboard.readText().then(t=>{const m=t.match(/https?:\/\/\S+/);if(!m){toast('No event link found in clipboard');return}if(typeof importUrl==='function')importUrl(m[0].replace(/[),.;]+$/,''));else{const input=document.querySelector('#importUrl');if(input){input.value=m[0];input.dispatchEvent(new Event('input'))}}}).catch(()=>toast('Clipboard permission was not granted'))}
const oldCalendar=calendar;
calendar=function(){let html=oldCalendar();html=html.replace('<section class="calendarShell">','<section class="calendarShell"><div class="calendarQuick"><button class="primary" id="addOwnEvent">＋ Add event</button><button class="ghost" id="calendarGps">⌖ Use GPS</button></div>');return html};
const oldSources=sources;
sources=function(){const base=oldSources();const launchers=`<section class="panel providerPanel"><span class="kicker">PROGRAMMED SOURCE LAUNCHERS</span><h3>Browse missing sources</h3><p><b>On iPhone:</b> open a provider below, open the event, tap Share → Copy, return to WTM, then tap <b>Import copied link</b>. On browsers that support PWA share targets, direct Share → WTM can work too.</p><div class="providerActions"><button class="primary" id="clipboardImport">Import copied link</button>${PROVIDERS.map(([n,u])=>`<a href="${u}" target="_blank" rel="noopener">${n} ↗</a>`).join('')}</div></section>`;return base+launchers};
const oldBind=bindDynamic;
bindDynamic=function(){oldBind();const add=document.querySelector('#addOwnEvent');if(add)add.onclick=customModal;const cg=document.querySelector('#calendarGps');if(cg)cg.onclick=useGps;const ci=document.querySelector('#clipboardImport');if(ci)ci.onclick=clipboardImport;updateGpsButton()};
function attachStatic(){const b=document.querySelector('#locationBtn');if(b)b.onclick=useGps;updateGpsButton();const params=new URLSearchParams(location.search);const share=params.get('share_url')||params.get('share_text');if(share){const m=share.match(/https?:\/\/\S+/);if(m&&typeof importUrl==='function'){setTimeout(()=>importUrl(m[0].replace(/[),.;]+$/,'')),650)}}}
window.addEventListener('load',attachStatic);
})();