(()=>{
const posterUrl=e=>'https://toolbox-nine-eta.vercel.app/api/wtm-poster?title='+encodeURIComponent(e.title||'Houston Event')+'&venue='+encodeURIComponent(e.venue||e.area||'Greater Houston');
function ensureArtwork(){for(const e of events){if(!e.image){e.image=posterUrl(e);e.generatedImage=true}}}
window.priceText=e=>{if(e.priceLabel)return e.priceLabel;if(e.priceMin!=null&&e.priceMax!=null){return Number(e.priceMin)===Number(e.priceMax)?(Number(e.priceMin)===0?'Free':'$'+Number(e.priceMin).toFixed(Number(e.priceMin)%1?2:0)):`$${Number(e.priceMin).toFixed(0)}–$${Number(e.priceMax).toFixed(0)}`}if(e.price!=null)return Number(e.price)===0?'Free':'From $'+Number(e.price).toFixed(Number(e.price)%1?2:0);return'Price unavailable'};
const baseMatches=matches;
matches=function(e){if(!baseMatches(e))return false;const priced=document.querySelector('#pricedOnly');if(priced?.checked&&e.price==null)return false;return true};
function addPriceToggle(){const grid=document.querySelector('.toggleGrid');if(grid&&!document.querySelector('#pricedOnly')){const l=document.createElement('label');l.innerHTML='<input id="pricedOnly" type="checkbox"> Known prices only';grid.appendChild(l);l.querySelector('input').addEventListener('change',render)}}
poster=function(e){const f=fmt(e);return`<article class="poster" data-detail="${attr(e.id)}"><img class="posterImg" src="${attr(e.image||posterUrl(e))}" alt="${attr(e.title)} event artwork" loading="lazy"><div class="posterTop"><span class="sourcePill">${safe(e.source)}</span><button class="heart ${saved.includes(e.id)?'on':''}" data-save="${attr(e.id)}" aria-label="Save event">♥</button></div><div class="posterBody"><div class="badgeRow"><span class="badge">${f.short}</span><span class="badge">${safe(priceText(e))}</span><span class="badge">${safe(e.area)}</span></div><h4>${safe(e.title)}</h4><small>${f.time} · ${safe(e.venue)}</small>${e.generatedImage?'<small class="generatedNote">WTM artwork</small>':''}</div></article>`};
listCard=function(e){const f=fmt(e);return`<article class="listCard"><img src="${attr(e.image||posterUrl(e))}" alt="${attr(e.title)} event artwork" loading="lazy"><div class="listBody"><span class="sourcePill">${safe(e.source)}</span><h3>${safe(e.title)}</h3><p>${f.date} · ${f.time}<br>${safe(e.venue)} · ${safe(e.area)}</p><div class="meta"><span>${safe(priceText(e))}</span><span>~${miles(e)} mi</span>${tags(e).map(t=>`<span>${safe(t)}</span>`).join('')}</div><div class="actions"><button class="primary" data-detail="${attr(e.id)}">Details</button><button data-plan="${attr(e.id)}">${plans.includes(e.id)?'✓ RSVP’d':'RSVP'}</button><button data-booked="${attr(e.id)}">${booked.includes(e.id)?'✓ Booked':'Booked'}</button></div></div></article>`};
window.detail=function(id){const e=events.find(x=>x.id===id);if(!e)return;const f=fmt(e),q=encodeURIComponent(e.address||e.venue+', '+e.area+', TX'),modal=document.querySelector('#modal'),description=e.description&&e.description.length>18?e.description:(tags(e).join(' · ')+' · '+solo(e)+'/10 solo-friendly');modal.className='modal';modal.innerHTML=`<section class="modalCard detailRich"><button class="close" id="close">×</button><img class="detailHero" src="${attr(e.image||posterUrl(e))}" alt="${attr(e.title)} event artwork"><div class="detailPad"><span class="sourcePill">${safe(e.source)}</span><h2>${safe(e.title)}</h2><p class="detailSummary">${safe(description)}</p><div class="detailFacts"><div><small>WHEN</small><b>${f.date}<br>${f.time}</b></div><div><small>WHERE</small><b>${safe(e.venue||e.area)}</b><span>${safe(e.address||e.area)}</span></div><div><small>PRICE</small><b>${safe(priceText(e))}</b><span>${e.priceSource?safe(e.priceSource):e.price==null?'No authoritative price published yet':''}</span></div><div><small>TRAVEL</small><b>~${miles(e)} mi</b><span>${safe(e.area)}</span></div></div><div class="detailSection"><h3>What to know</h3><div class="meta">${tags(e).map(x=>`<span>${safe(x)}</span>`).join('')}<span>Solo ${solo(e)}/10</span>${e.zip?`<span>ZIP ${safe(e.zip)}</span>`:''}<span>${safe(e.sourceMode||'live source')}</span></div>${e.description?`<p>${safe(e.description)}</p>`:'<p>WTM has the event, venue, time and booking source. Pricing is only shown when an authoritative source exposes it.</p>'}</div><iframe loading="lazy" title="Event map" src="https://www.google.com/maps?q=${q}&output=embed"></iframe><div class="actions"><a class="primary" href="${attr(e.url)}" target="_blank" rel="noopener">Tickets / official page</a><a href="https://www.google.com/maps/dir/?api=1&destination=${q}" target="_blank" rel="noopener">Directions</a><button id="cal">Add to Calendar</button><button id="life">Add to Life OS</button><button id="rsvp">${plans.includes(id)?'Remove RSVP':'Mark RSVP’d'}</button><button id="booked">${booked.includes(id)?'Remove Booked':'Mark Booked'}</button></div></div></section>`;const close=()=>modal.className='modal hide';document.querySelector('#close').onclick=close;modal.onclick=x=>{if(x.target===modal)close()};document.querySelector('#rsvp').onclick=()=>{plans=plans.includes(id)?plans.filter(x=>x!==id):[...plans,id];store('wtm-plans',plans);close();render()};document.querySelector('#booked').onclick=()=>{booked=booked.includes(id)?booked.filter(x=>x!==id):[...booked,id];store('wtm-booked',booked);if(booked.includes(id)&&!plans.includes(id)){plans=[...plans,id];store('wtm-plans',plans)}close();render()};document.querySelector('#cal').onclick=()=>ics(e);document.querySelector('#life').onclick=()=>{const p=encodeURIComponent(JSON.stringify({title:e.title,date:e.date,venue:e.venue,address:e.address,source:'WTM',url:e.url}));window.open('https://life-transition-command-center.vercel.app/?wtm='+p,'_blank')}};
const baseRender=render;render=function(){ensureArtwork();baseRender();addPriceToggle()};
ensureArtwork();addPriceToggle();render();
})();