(()=>{
const oldMoney=money;
window.money=function(v,e){if(e?.priceLabel)return e.priceLabel;if(v===0)return'Free';if(v==null)return'Price unavailable';return'$'+Number(v).toFixed(Number(v)%1?2:0)};
function fallbackKind(e){const ts=tags(e);return ts.includes('Sports')?'sports':ts.includes('Music')?'music':'other'}
function fallbackEmoji(e){const x=(e.title+' '+e.venue).toLowerCase();if(/texans|football|nfl/.test(x))return'🏈';if(/astros|baseball|mlb/.test(x))return'⚾';if(/rockets|basketball|nba/.test(x))return'🏀';if(/dynamo|soccer|mls/.test(x))return'⚽';if(/concert|music|tour|singer|band|jazz|r&b/.test(x))return'♫';return'✦'}
function fallbackArt(e){const k=fallbackKind(e),f=fmt(e);return`<div class="fallbackMark ${k}"><div class="sportGlyph">${fallbackEmoji(e)}</div><div class="matchup">${safe(e.title)}</div><div class="venueLine">${safe(e.venue||e.area)} · ${f.short}</div></div>`}
window.posterMedia=function(e){return e.image?`<img class="posterImg" src="${attr(e.image)}" alt="${attr(e.title)} event flyer" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">${`<div style="display:none" class="fallbackMark ${fallbackKind(e)}"><div class="sportGlyph">${fallbackEmoji(e)}</div><div class="matchup">${safe(e.title)}</div><div class="venueLine">${safe(e.venue||e.area)}</div></div>`}`:fallbackArt(e)}
window.poster=function(e){const f=fmt(e),price=e.priceLabel||money(e.price,e);return`<article class="poster" data-detail="${attr(e.id)}">${posterMedia(e)}<div class="posterTop"><span class="sourcePill">${safe(e.source)}</span><button class="heart ${saved.includes(e.id)?'on':''}" data-save="${attr(e.id)}" aria-label="Save event">♡</button></div><div class="posterBody"><div class="badgeRow"><span class="badge">${f.short}</span>${tags(e).slice(0,1).map(t=>`<span class="badge">${safe(t)}</span>`).join('')}</div><h4>${safe(e.title)}</h4><small>${safe(e.venue||e.area)} · ${f.time}</small><div class="priceTag">${safe(price)}</div></div></article>`}
function feedGrid(list){return`<div class="feedGrid">${list.map(poster).join('')}</div>`}
function cap(list,n=24){return list.slice(0,n)}
window.discover=function(){const list=visible().slice().sort((a,b)=>new Date(a.date)-new Date(b.date)),q=$('#search')?.value.trim()||'',loc=$('#locationSearch')?.value.trim()||'';if(!list.length)return`<div class="empty"><h3>No matches</h3><p>Try another search or clear filters.</p><button class="ghost" id="emptyReset">Reset search + filters</button></div>`;if(q||loc||quick!=='all'||filters.category!=='all'||filters.price!==''||filters.free||filters.solo||filters.area!=='all'||filters.source!=='all'){return`<section class="searchSummary"><b>${list.length} matching events</b><small>Full live feed</small></section>${feedGrid(list)}`}
const sports=list.filter(e=>tags(e).includes('Sports')),music=list.filter(e=>tags(e).includes('Music')),weekend=list.filter(e=>datePass(e,'weekend')),cheap=list.filter(e=>e.price!=null&&Number(e.price)<=25),social=list.filter(e=>/ladies|girls|social|brunch|rooftop|party|cocktail|wine|date/i.test(textBlob(e))),creative=list.filter(e=>tags(e).includes('Artsy'));
return`${row('🔥 This Weekend','',cap(weekend,20))}${row('🏟 Sports & Games','',cap(sports,24))}${row('♫ Concerts & Music','',cap(music,24))}${row('💸 Free + Under $25','',cap(cheap,20))}${row('✨ Social & Date Night','',cap(social,20))}${row('🎨 Creative & Artsy','',cap(creative,20))}<section class="rowSection"><div class="rowHead"><div><h3>All Upcoming Events</h3></div><small>${list.length} events</small></div>${feedGrid(list)}</section>`}
const oldTags=tags;window.tags=function(e){const t=oldTags(e);const x=(e.title+' '+e.description+' '+e.source).toLowerCase();if(/texans|astros|rockets|dynamo|dash|nfl|nba|mlb|mls|football|basketball|baseball|soccer|sporting/.test(x)&&!t.includes('Sports'))t.unshift('Sports');return[...new Set(t)]}
const chips=document.querySelector('#chips');if(chips&&!chips.querySelector('[data-filter="sports"]')){const b=document.createElement('button');b.dataset.filter='sports';b.textContent='Sports';const music=chips.querySelector('[data-filter="music"]');chips.insertBefore(b,music||chips.firstChild);b.onclick=()=>{quick='sports';$$('#chips button').forEach(x=>x.classList.toggle('active',x===b));render()}}
const oldMatches=matches;window.matches=function(e){if(quick==='sports'&&!tags(e).includes('Sports'))return false;return oldMatches(e)};
const oldRender=render;window.render=function(){oldRender();if(tab==='discover'){const t=document.querySelector('#title');if(t)t.textContent='What’s happening around Houston';const y=document.querySelector('#eyebrow');if(y)y.textContent='LIVE DISCOVERY'}document.body.classList.toggle('modalOpen',!document.querySelector('#modal')?.classList.contains('hide'))};
const obs=new MutationObserver(()=>{const m=document.querySelector('#modal');const open=m&&!m.classList.contains('hide');document.documentElement.style.overflow=open?'hidden':'';document.body.style.overflow=open?'hidden':''});obs.observe(document.querySelector('#modal'),{attributes:true,attributeFilter:['class']});
setTimeout(()=>render(),50);
})();