(()=>{
const FEVER_API='https://toolbox-nine-eta.vercel.app/api/wtm-fever-events',FEVER_REDIRECT='https://wtm-whats-the-move.vercel.app/fever-callback.html',FEVER_RESOURCE='https://data-search.apigw.feverup.com/mcp';
const oldBind=bind;
function token(){try{return JSON.parse(localStorage.getItem('wtm-fever-token')||'null')}catch{return null}}
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function pkce(){const bytes=crypto.getRandomValues(new Uint8Array(48)),verifier=b64(bytes),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return{verifier,challenge:b64(digest)}}
async function validToken(){let t=token();if(!t)return null;const expires=(t.obtained_at||0)+(Number(t.expires_in||3600)*1000);if(Date.now()<expires-120000)return t.access_token;if(!t.refresh_token)return null;try{const r=await fetch('https://toolbox-nine-eta.vercel.app/api/wtm-fever-token',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:t.client_id,client_secret:t.client_secret,refresh_token:t.refresh_token})}),d=await r.json();if(!r.ok)throw Error();t={...t,...d,refresh_token:d.refresh_token||t.refresh_token,obtained_at:Date.now()};localStorage.setItem('wtm-fever-token',JSON.stringify(t));return t.access_token}catch{return null}}
async function connectFever(){if(token())return syncFever(true);const st=document.getElementById('feverStatus');if(st)st.textContent='Preparing Fever authorization…';try{const r=await fetch('https://toolbox-nine-eta.vercel.app/api/wtm-fever-register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({redirect_uri:FEVER_REDIRECT})}),d=await r.json();if(!r.ok)throw Error(d.error||'Fever registration failed');const {verifier,challenge}=await pkce(),stateKey=b64(crypto.getRandomValues(new Uint8Array(24)));localStorage.setItem('wtm-fever-oauth',JSON.stringify({client_id:d.client_id,client_secret:d.client_secret,code_verifier:verifier,state:stateKey,redirect_uri:FEVER_REDIRECT}));const u=new URL(d.authorization_endpoint);for(const [k,v] of Object.entries({response_type:'code',client_id:d.client_id,redirect_uri:FEVER_REDIRECT,scope:'openid',resource:FEVER_RESOURCE,state:stateKey,code_challenge:challenge,code_challenge_method:'S256'}))u.searchParams.set(k,v);location.href=u.toString()}catch(e){if(st)st.textContent='Fever connection failed: '+e.message}}
async function syncFever(show=false){const access=await validToken();if(!access)return 0;const st=document.getElementById('feverStatus');if(show&&st)st.textContent='Syncing Fever Houston…';try{const r=await fetch(FEVER_API,{headers:{authorization:'Bearer '+access},cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Fever sync failed');state.events=dedupe([...(d.events||[]),...state.events]);state.statuses=[{source:'Fever',mode:'official real-time OAuth discovery',status:'live',count:d.count||0},...state.statuses.filter(x=>x.source!=='Fever')];render();return d.count||0}catch(e){if(st)st.textContent='Fever is connected, but this sync failed. Tap Retry.';return 0}}
function posterUrl(e){return 'https://toolbox-nine-eta.vercel.app/api/wtm-poster?title='+encodeURIComponent(e.title||'Houston Event')+'&venue='+encodeURIComponent(e.venue||e.area||'Greater Houston')+'&source='+encodeURIComponent(e.source||'WTM')}
media=function(e){const fallback=`<img class="generatedPoster" src="${attr(posterUrl(e))}" alt="WTM artwork for ${attr(e.title)}" loading="lazy">`;return e.image?`${fallback}<img class="officialPoster" src="${attr(e.image)}" alt="${attr(e.title)} flyer" loading="lazy" onerror="this.remove()">`:fallback};
sourcePage=function(){const fever=!!token(),known=[...state.statuses],extras=[['Ticketmaster','Official Discovery API','setup-required'],['Fever','Official real-time OAuth discovery',fever?'connected':'connect-once'],['POSH','Public marketplace; no documented attendee catalog API','public-indexed'],['AXS / 713 Music Hall','Covered via venues + ticket inventory','partial'],['DICE','Venue/ticket handoff + primary-source coverage','partial'],['Gametime','Covered by teams + venues + Ticketmaster','coverage-via-primary'],['Total Wine Events','Dedicated source adapter needed','adapter-needed']].map(([source,mode,status])=>({source,mode,status,count:0})),seen=new Set(known.map(x=>x.source)),all=[...known,...extras.filter(x=>x.source==='Fever'||!seen.has(x.source))];return`<div class="sourcesPage"><div><div class="rowHeader"><h2>Sources & Sync</h2><span>${state.events.length} aggregated events</span></div><div class="sourceList">${all.map(s=>`<div class="sourceRow"><div><b>${esc(s.source||'Source')}</b><small>${esc(s.mode||s.url||'feed')}</small></div><div class="${statusClass(s)}">${esc(s.status||'unknown')}${s.count?` · ${s.count}`:''}</div></div>`).join('')}</div></div><aside class="sidePanel"><h3>Fever</h3><p>Official real-time Houston discovery. Fever returns prices, availability, descriptions and pagination through its OAuth event-discovery service.</p><button id="connectFever" class="primary" style="width:100%">${fever?'Sync Fever now':'Connect Fever'}</button>${fever?'<button id="disconnectFever" class="ghost" style="width:100%;margin-top:8px">Disconnect Fever</button>':''}<div id="feverStatus" class="meta" style="margin-top:8px">${fever?'Connected. Fever joins Discover automatically.':'Authorize once; no event-by-event imports.'}</div><h3 style="margin-top:22px">POSH + other protected catalogs</h3><p>WTM will not defeat anti-bot controls. POSH events are covered from primary venues/ticketing where possible. A sanctioned search-index connector can supplement publicly indexed POSH event pages if you want broader POSH-specific coverage.</p><h3 style="margin-top:22px">Artwork</h3><p>Official flyers stay first choice. Missing artwork now gets a mockup-style event poster with sport-specific or concert styling instead of the generic purple fallback.</p></aside></div>`};
bind=function(){oldBind();const cf=document.getElementById('connectFever');if(cf)cf.onclick=connectFever;const df=document.getElementById('disconnectFever');if(df)df.onclick=()=>{localStorage.removeItem('wtm-fever-token');localStorage.removeItem('wtm-fever-oauth');state.events=state.events.filter(e=>e.source!=='Fever');state.statuses=state.statuses.filter(x=>x.source!=='Fever');render()}};
setTimeout(()=>{render();syncFever(false)},350);
})();