(()=>{
const AGG16='https://toolbox-nine-eta.vercel.app/api/wtm-aggregate-v12';
function media16(e){const fb=fallback(e);if(!e.image)return fb;return`<div class="mediaStack">${fb}<img class="officialMedia" src="${attr(e.image)}" alt="${attr(e.title)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.style.display='none'"></div>`}
media=media16;
function r16(title,list){if(!list.length)return'';return row(title,[...list].sort((a,b)=>pscore(b)-pscore(a)||new Date(a.date)-new Date(b.date)))}
discover=function(){
 const list=visible();if(!list.length)return`<div class="empty"><h3>No events match</h3><p>Clear a filter or broaden your search.</p></div>`;
 const filtered=state.search||state.quick!=='all'||state.filters.price!==''||state.filters.date!=='any'||state.filters.area!=='all'||state.filters.source!=='all'||state.filters.category!=='all'||state.filters.distance!=='50'||state.filters.known;
 if(filtered)return`<section class="row"><div class="rowHeader"><h2>Search results</h2><span>${list.length} events</span></div><div class="feedGrid">${list.map(eventCard).join('')}</div></section>`;
 const fy=[...list].sort((a,b)=>pscore(b)-pscore(a)).slice(0,24),wk=list.filter(e=>datePass(e,'weekend')),sports=list.filter(e=>category(e)==='Sports'),pro=sports.filter(e=>/texans|astros|rockets|dynamo|dash|nfl|mlb|nba|mls|nwsl/.test(searchText(e))&&!/college|cougars|owls|texas southern|tigers football/.test(searchText(e))),college=sports.filter(e=>/college football|cougars football|owls football|texas southern|university of houston athletics|rice athletics/.test(searchText(e))),soccer=sports.filter(e=>/dynamo|dash|soccer|mls|nwsl/.test(searchText(e))),music=list.filter(e=>category(e)==='Music'),cheap=list.filter(e=>minPrice(e)!=null&&minPrice(e)<=25),solo=list.filter(e=>soloScore(e)>=9),food=list.filter(e=>category(e)==='Food + Wine'),art=list.filter(e=>category(e)==='Artsy'),out=list.filter(e=>category(e)==='Outdoors');
 return`${r16('✨ For You',fy)}${r16('🔥 This Weekend',wk)}${r16('🏟 Pro Sports',pro)}${r16('🏈 College Football',college)}${r16('⚽ Soccer · Dynamo + Dash',soccer)}${r16('♫ Concerts & Music',music)}${r16('💸 Free + Under $25',cheap)}${r16('☕ Solo-Friendly',solo)}${r16('🍷 Food + Drinks',food)}${r16('🎨 Creative & Artsy',art)}${r16('🌿 Outdoors',out)}<div class="browseAllWrap"><button id="browseAll" class="ghost">${state._browseAll?'Hide all events':`Browse all ${list.length} events`}</button></div>${state._browseAll?`<section class="row"><div class="feedGrid compactBrowse">${list.map(eventCard).join('')}</div></section>`:''}`;
};
sourcePage=function(){
 const fever=state.statuses.find(s=>s.source==='Fever'),pub=state.statuses.find(s=>s.source==='Public Index'),tm=state.statuses.find(s=>s.source==='Ticketmaster'),sports=state.statuses.find(s=>s.source==='Houston Sports');
 const rows=state.statuses.filter(s=>!['Fever','Public Index','Ticketmaster','Houston Sports'].includes(s.source));
 return`<section class="sourceSetupV16"><div class="rowHeader"><h2>Sources</h2><span>${state.events.length} live upcoming events</span></div><div class="setupGridV15">
 <div class="setupCardV15 success"><div class="setupIcon">🔥</div><div><h3>Fever</h3><p>Automatic public Houston catalog. No Fever login or OAuth connection is required.</p><div class="setupBadge live">${fever?.status==='live'?`Live · ${fever.count||0} events`:'Syncing public feed'}</div></div></div>
 <div class="setupCardV15 ${tm?.status==='live'?'success':'needs'}"><div class="setupIcon">🎟️</div><div><h3>Ticketmaster</h3><p>Uses Ticketmaster’s Consumer Key as a server-side environment variable. The key never needs to live on your phone.</p><div class="setupBadge ${tm?.status==='live'?'live':'partial'}">${tm?.status==='live'?`Live · ${tm.count||0} events`:'Optional setup'}</div><button id="tmGuide" class="ghost">Consumer Key setup</button></div></div>
 <div class="setupCardV15 success"><div class="setupIcon">🏟️</div><div><h3>Houston Sports</h3><p>Dynamo, Dash, Dynamo 2, University of Houston, Rice, Texas Southern and Rockets schedules are merged into Discover.</p><div class="setupBadge live">${sports?.count!=null?`${sports.count} upcoming games`:'Official schedules active'}</div></div></div>
 <div class="setupCardV15 ${pub?.status==='live'?'success':'needs'}"><div class="setupIcon">🧭</div><div><h3>Public Index</h3><p>Optional discovery layer for public POSH, DICE, Bucket Listers, Do713, Houstonia and Total Wine pages.</p><div class="setupBadge ${pub?.status==='live'?'live':'partial'}">${pub?.status==='live'?`Live · ${pub.count||0} events`:'Optional Brave Search key'}</div><button id="indexGuide" class="ghost">Public Index setup</button></div></div>
 </div><div id="setupGuideBox"></div><details class="statusDetails"><summary>Advanced source health (${rows.length})</summary><div class="sourceList">${rows.map(s=>`<div class="sourceRow"><div><b>${esc(s.source||'Source')}</b><small>${esc(s.mode||s.url||'feed')}</small></div><div class="${statusClass(s)}">${esc(s.status||'unknown')}${s.count!=null?` · ${s.count}`:''}</div></div>`).join('')}</div></details></section>`;
};
const bind16=bind;bind=function(){bind16();const box=document.getElementById('setupGuideBox'),t=document.getElementById('tmGuide');if(t)t.onclick=()=>{box.innerHTML=`<div class="guideCard"><button class="guideClose" onclick="this.parentElement.remove()">×</button><h3>Ticketmaster Consumer Key</h3><ol><li>Sign in at Ticketmaster Developer and create an app.</li><li>Copy the app’s <b>Consumer Key</b>.</li><li>In Vercel open the <b>toolbox</b> project → Settings → Environment Variables. Add <code>TICKETMASTER_API_KEY</code>, then redeploy Toolbox.</li></ol><p>WTM’s Ticketmaster endpoint runs from Toolbox, so the key belongs on that project—not the standalone WTM shell.</p></div>`};const i=document.getElementById('indexGuide');if(i)i.onclick=()=>{box.innerHTML=`<div class="guideCard"><button class="guideClose" onclick="this.parentElement.remove()">×</button><h3>Optional public index</h3><ol><li>Create a Brave Search API key.</li><li>In Vercel open <b>toolbox</b> → Settings → Environment Variables.</li><li>Add <code>BRAVE_SEARCH_API_KEY</code> and redeploy.</li></ol><p>This is only for finding publicly indexed POSH/DICE/etc. pages; WTM’s primary feeds work without it.</p></div>`};};
async function refresh16(){try{const r=await fetch(AGG16+'?v=16&t='+Date.now(),{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Aggregate sync failed');state.events=dedupe(d.events||[]);state.statuses=d.statuses||[];state.loading=false;render()}catch(err){console.warn('WTM v16 refresh failed',err)}}
setTimeout(refresh16,120);
setInterval(refresh16,10*60*1000);
})();