const SOURCES=[['Luma','https://lu.ma/houston'],['Fever','https://feverup.com/en/houston'],['DICE','https://dice.fm/browse/houston'],['Do713','https://do713.com/events'],['Houstonia','https://www.houstoniamag.com/calendar'],['Discovery Green','https://www.discoverygreen.com/events/'],['POST Houston','https://www.posthtx.com/event'],['Museum Calendar','https://www.mfah.org/calendar'],['Total Wine','https://www.totalwine.com/events'],['Bucket Listers','https://bucketlisters.com/experience/houston'],['Gametime','https://gametime.co/houston-tickets/metros/hou'],['Eventbrite','https://www.eventbrite.com/d/tx--houston/events/'],['POSH','https://posh.vip/explore/houston']];
const ALLOWED=['eventbrite.com','lu.ma','posh.vip','bucketlisters.com','feverup.com','dice.fm','do713.com','houstoniamag.com','discoverygreen.com','posthtx.com','mfah.org','gametime.co','totalwine.com','instagram.com','visitgalveston.com'];
const LOCAL=/\b(houston|galveston|sugar land|stafford|missouri city|katy|cinco ranch|cypress|the woodlands|woodlands|spring|humble|kingwood|pearland|friendswood|clear lake|webster|league city|bellaire|pasadena|baytown|tomball|richmond|rosenberg|texas city|kemah|seabrook|deer park|houston,? tx|tx,? 77\d{3})\b/i;
const ONLINE=/\b(online|virtual|livestream|webinar|zoom)\b/i;
const arr=v=>Array.isArray(v)?v:[v];const strip=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
function sourceFromUrl(url){const host=new URL(url).hostname.replace(/^www\./,'');const m=[['eventbrite.com','Eventbrite'],['lu.ma','Luma'],['posh.vip','POSH'],['bucketlisters.com','Bucket Listers'],['feverup.com','Fever'],['dice.fm','DICE'],['do713.com','Do713'],['houstoniamag.com','Houstonia'],['discoverygreen.com','Discovery Green'],['posthtx.com','POST Houston'],['mfah.org','Museum Calendar'],['gametime.co','Gametime'],['totalwine.com','Total Wine'],['instagram.com','Instagram'],['visitgalveston.com','Galveston']];return (m.find(([d])=>host.endsWith(d))||[])[1]||host}
function areaFrom(s=''){s=s.toLowerCase();for(const [x,n] of [['galveston','Galveston'],['sugar land','Sugar Land'],['stafford','Stafford'],['missouri city','Missouri City'],['woodlands','The Woodlands'],['katy','Katy'],['pearland','Pearland'],['friendswood','Friendswood'],['league city','League City'],['clear lake','Clear Lake'],['webster','Webster'],['cypress','Cypress'],['spring','Spring'],['humble','Humble'],['kingwood','Kingwood'],['downtown','Downtown'],['montrose','Montrose'],['heights','Heights']])if(s.includes(x))return n;return 'Greater Houston'}
function norm(i,source,sourceUrl){const l=i.location||{},a=typeof l==='string'?l:(l.address||{}),address=typeof a==='string'?a:[a.streetAddress,a.addressLocality,a.addressRegion,a.postalCode].filter(Boolean).join(', '),venue=strip(l.name||address||''),start=i.startDate||i.startTime||i.date;if(!i.name||!start)return null;const d=new Date(start);if(Number.isNaN(d.getTime())||d.getTime()<Date.now()-3600000)return null;const o=arr(i.offers||[])[0]||{},raw=o.price,price=raw===0||raw==='0'?0:(raw?Number(raw):null);return{id:(source+':'+(i['@id']||i.url||i.name)+':'+start).replace(/\s+/g,'_').slice(0,240),title:strip(i.name),source,date:d.toISOString(),area:areaFrom(venue+' '+address),venue:venue||'Houston area',address:strip(address),price:Number.isFinite(price)?price:null,url:i.url||o.url||sourceUrl,description:strip(i.description||''),image:typeof i.image==='string'?i.image:(arr(i.image)[0]?.url||arr(i.image)[0]||'')}}
function extract(html,source,url){const out=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{for(const root of arr(JSON.parse(m[1].trim()))){for(const i of root?.['@graph']?arr(root['@graph']):[root]){if(arr(i?.['@type']).includes('Event')){const n=norm(i,source,url);if(n)out.push(n)}for(const el of arr(i?.itemListElement||[])){const v=el?.item||el;if(arr(v?.['@type']).includes('Event')){const n=norm(v,source,url);if(n)out.push(n)}}}}}catch{}}return out}
function isLocal(e){const text=[e.title,e.venue,e.address,e.description].join(' ');if(ONLINE.test(text)&&!LOCAL.test(e.address+' '+e.venue))return false;try{const h=new URL(e.url).hostname.toLowerCase();if(h.includes('eventbrite.')&&h!=='www.eventbrite.com'&&h!=='eventbrite.com')return false}catch{}return LOCAL.test(e.address+' '+e.venue)||((e.source==='Luma'||e.source==='Eventbrite')&&/houston/i.test(text))}
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; WTM/1.0)','accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');if(req.query?.url){let u;try{u=new URL(String(req.query.url));const h=u.hostname.replace(/^www\./,'');if(!['http:','https:'].includes(u.protocol)||!ALLOWED.some(d=>h===d||h.endsWith('.'+d)))throw 0}catch{return res.status(400).json({error:'That source is not enabled for WTM link import.'})}try{const source=sourceFromUrl(u.toString()),events=extract(await get(u.toString()),source,u.toString());if(!events.length)return res.status(422).json({error:'No structured event details were found on that page.',source});return res.json({event:events[0],alternates:events.slice(1,5)})}catch(e){return res.status(502).json({error:'WTM could not read that event page.',detail:String(e.message||e)})}}
const results=await Promise.all(SOURCES.map(async([source,url])=>{try{const raw=extract(await get(url),source,url),events=raw.filter(isLocal);return{source,url,status:events.length?'live':raw.length?'filtered-no-local-events':'no-structured-events',count:events.length,events}}catch(e){return{source,url,status:'unavailable',count:0,error:String(e.message||e),events:[]}}}));const seen=new Set(),events=[];for(const r of results)for(const e of r.events){const k=(e.title+'|'+e.date+'|'+e.venue).toLowerCase();if(!seen.has(k)){seen.add(k);events.push(e)}}events.sort((a,b)=>new Date(a.date)-new Date(b.date));res.json({generatedAt:new Date().toISOString(),region:'Greater Houston + Galveston',events,statuses:results.map(({events,...r})=>r)});};
