const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#8217;|&rsquo;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const abs=(h,b)=>{try{return new URL(h,b).toString()}catch{return''}};
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),6500);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; WTM/2.6; +https://wtm-whats-the-move.vercel.app)','accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return{html:await r.text(),url:r.url}}finally{clearTimeout(t)}}
function meta(html,name){for(const p of[new RegExp('<meta[^>]+(?:property|name)=["\\\']'+name.replace(':','\\:')+'["\\\'][^>]+content=["\\\']([^"\\\']+)["\\\']','i'),new RegExp('<meta[^>]+content=["\\\']([^"\\\']+)["\\\'][^>]+(?:property|name)=["\\\']'+name.replace(':','\\:')+'["\\\']','i')]){const m=html.match(p);if(m)return strip(m[1])}return''}
function links(html,base,re,limit=40){const out=[],seen=new Set(),rx=/href=["']([^"'#]+)["']/gi;let m;while((m=rx.exec(html))&&out.length<limit){const u=abs(m[1],base);if(!u||seen.has(u))continue;let p='';try{p=new URL(u).pathname}catch{}if(re.test(p)){seen.add(u);out.push(u)}}return out}
function parseDateTime(text){const dm=text.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s+(20\d{2})\b/i);if(!dm)return null;const after=text.slice(Math.max(0,text.indexOf(dm[0])),Math.max(0,text.indexOf(dm[0]))+500),tm=after.match(/\b(\d{1,2}:\d{2}\s*(?:am|pm))\b/i);const d=new Date(`${dm[1]} ${dm[2]}, ${dm[3]} ${tm?tm[1]:'12:00 PM'} CDT`);return Number.isNaN(d.getTime())?null:d.toISOString()}
function price(text){if(/\bfree admission\b|\bfree event\b|\bfree fitness\b|\bmost events are free\b/i.test(text))return{price:0,priceMin:0,priceMax:0,priceLabel:'Free',priceSource:'official event page'};const m=text.match(/(?:admission(?: is)?|tickets?(?: are)?|general admission)[^$]{0,45}\$\s*([0-9]+(?:\.[0-9]{1,2})?)/i);if(m){const n=Number(m[1]);return{price:n,priceMin:n,priceMax:n,priceLabel:'$'+n,priceSource:'official event page'}}return{}}
function discoveryEvent(html,url){const text=strip(html),title=(meta(html,'og:title')||((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]||'')).replace(/\s*[-|]\s*Discovery Green.*$/i,'').trim(),date=parseDateTime(text);if(!title||!date||new Date(date).getTime()<Date.now()-86400000)return null;const venue=((text.match(/THIS EVENT IS LOCATED\s*@\s*([A-Za-z0-9'’ &.-]{2,80})/i)||[])[1]||'Discovery Green').trim();return{id:'Discovery Green:'+url+':'+date,title,source:'Discovery Green',date,endDate:null,area:'Downtown',venue,address:'1500 McKinney St, Houston, TX 77010',zip:'77010',...price(text),url,description:meta(html,'og:description')||'',image:meta(html,'og:image')||'',lat:29.7531,lng:-95.3597,sourceMode:'official venue calendar'}}
function nrgEvent(html,url){const text=strip(html),title=(meta(html,'og:title')||((html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)||[])[1]||'')).replace(/\s*[-|]\s*NRG Park.*$/i,'').trim(),date=parseDateTime(text);if(!title||!date||new Date(date).getTime()<Date.now()-86400000)return null;const venue=(text.match(/\b(NRG Stadium|NRG Center|NRG Arena|NRG Astrodome)\b/i)||[])[1]||'NRG Park';return{id:'NRG rich:'+url+':'+date,title,source:'NRG Park',date,endDate:null,area:'Greater Houston',venue,address:'1 NRG Pkwy, Houston, TX 77054',zip:'77054',...price(text),url,description:meta(html,'og:description')||'Official NRG Park event listing.',image:meta(html,'og:image')||'',lat:29.6847,lng:-95.4107,sourceMode:'official venue detail'}}
async function crawl(name,indexUrl,re,parser,limit){try{const idx=await get(indexUrl),urls=links(idx.html,idx.url,re,limit),pages=await Promise.all(urls.map(async u=>{try{const x=await get(u);return parser(x.html,u)}catch{return null}})),events=pages.filter(Boolean);return{source:name,url:indexUrl,mode:'official venue detail adapter',status:events.length?'live':'no-readable-events',count:events.length,events}}catch(e){return{source:name,url:indexUrl,mode:'official venue detail adapter',status:'unavailable',count:0,error:String(e.message||e),events:[]}}}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');const [dg,nrg]=await Promise.all([crawl('Discovery Green','https://www.discoverygreen.com/upcoming-events/',/\/event\//i,discoveryEvent,28),crawl('NRG Park Rich','https://www.nrgpark.com/events-tickets/',/\/event\//i,nrgEvent,22)]);res.json({generatedAt:new Date().toISOString(),events:[...dg.events,...nrg.events],statuses:[{...dg,events:undefined},{...nrg,events:undefined}]})};