const ENDPOINTS=['https://toolbox-nine-eta.vercel.app/api/wtm-events','https://toolbox-nine-eta.vercel.app/api/wtm-primary','https://toolbox-nine-eta.vercel.app/api/wtm-venues'];
function dedupe(list){const seen=new Set();return list.filter(e=>{if(!e||!e.title||!e.date)return false;const day=String(e.date).slice(0,10),k=[String(e.title).toLowerCase().replace(/[^a-z0-9]+/g,' '),day,String(e.venue||'').toLowerCase()].join('|');if(seen.has(k))return false;seen.add(k);return true})}
const num=x=>{const n=Number(String(x).replace(/[$,]/g,''));return Number.isFinite(n)?n:null};
function explicitFree(e){return /\b(free admission|free entry|free tickets?|free before|free b4|no cover|complimentary)\b/i.test([e.title,e.description].join(' '))}
function offerPrices(node,out=[]){if(!node||typeof node!=='object')return out;const types=Array.isArray(node['@type'])?node['@type']:[node['@type']];if(types.some(x=>String(x).toLowerCase()==='event')){const offers=Array.isArray(node.offers)?node.offers:[node.offers].filter(Boolean);for(const o of offers){if(!o||typeof o!=='object')continue;for(const k of ['lowPrice','highPrice','price']){const n=num(o[k]);if(n!=null&&n>=0&&n<5000)out.push(n)}if(o.priceSpecification){const p=Array.isArray(o.priceSpecification)?o.priceSpecification:[o.priceSpecification];for(const s of p){for(const k of ['minPrice','maxPrice','price']){const n=num(s?.[k]);if(n!=null&&n>=0&&n<5000)out.push(n)}}}}}for(const v of Object.values(node)){if(v&&typeof v==='object'){if(Array.isArray(v))v.forEach(x=>offerPrices(x,out));else offerPrices(v,out)}}return out}
function priceFromHtml(html=''){const vals=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const root=JSON.parse(m[1].trim());offerPrices(root,vals)}catch{}}if(vals.length){const low=Math.min(...vals),high=Math.max(...vals);return{price:low,priceMin:low,priceMax:high,priceLabel:low===high?(low===0?'Free':`$${low}`):`$${low}–$${high}`,priceSource:'structured ticket offer'}}if(/\bfree admission\b|\bfree tickets?\b|\bno cover\b/i.test(html))return{price:0,priceMin:0,priceMax:0,priceLabel:'Free',priceSource:'explicit event text'};return null}
async function fetchPrice(e){if(e.price!=null){const p=Number(e.price);return{...e,priceMin:e.priceMin??p,priceMax:e.priceMax??p,priceLabel:e.priceLabel||(p===0?'Free':`$${p}`),priceSource:e.priceSource||'source feed'}}if(explicitFree(e))return{...e,price:0,priceMin:0,priceMax:0,priceLabel:'Free',priceSource:'explicit source text'};if(!/^https?:/i.test(e.url||''))return e;if(!/eventbrite\.com|toyotacenter\.com|luma\.com|lu\.ma/i.test(e.url))return e;const c=new AbortController(),t=setTimeout(()=>c.abort(),4500);try{const r=await fetch(e.url,{headers:{'user-agent':'Mozilla/5.0 (compatible; WTM/2.4; +https://wtm-whats-the-move.vercel.app)','accept':'text/html'},redirect:'follow',signal:c.signal});if(!r.ok)return e;const html=await r.text(),p=priceFromHtml(html);return p?{...e,...p,priceUrl:r.url}:e}catch{return e}finally{clearTimeout(t)}}
async function enrichPrices(events){const candidates=events.map((e,i)=>({e,i})).filter(({e})=>e.price==null&&(e.source==='Eventbrite'||e.source==='Toyota Center'||e.source==='Luma')).slice(0,32);const updated=await Promise.all(candidates.map(({e})=>fetchPrice(e)));const map=new Map(candidates.map((x,j)=>[x.i,updated[j]]));return events.map((e,i)=>map.get(i)||known(e))}
function known(e){if(e.price!=null){const p=Number(e.price);return{...e,priceMin:e.priceMin??p,priceMax:e.priceMax??p,priceLabel:e.priceLabel||(p===0?'Free':`$${p}`)}}if(explicitFree(e))return{...e,price:0,priceMin:0,priceMax:0,priceLabel:'Free',priceSource:'explicit source text'};return e}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','s-maxage=180, stale-while-revalidate=600');const stamp=Date.now();const payloads=await Promise.all(ENDPOINTS.map(async url=>{try{const r=await fetch(url+'?unified='+stamp,{headers:{accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}catch(e){return{events:[],statuses:[{source:url.split('/').pop(),status:'error',count:0,error:String(e.message||e)}]}}}));let events=dedupe(payloads.flatMap(p=>p.events||[])).sort((a,b)=>new Date(a.date)-new Date(b.date));events=await enrichPrices(events);const statusMap=new Map();for(const s of payloads.flatMap(p=>p.statuses||[])){const prev=statusMap.get(s.source);if(!prev||Number(s.count||0)>Number(prev.count||0)||s.status==='live')statusMap.set(s.source,s)}const priced=events.filter(e=>e.price!=null).length;res.json({generatedAt:new Date().toISOString(),region:'Greater Houston + Galveston',count:events.length,pricedCount:priced,events,statuses:[...statusMap.values()],feeds:ENDPOINTS})};