const SOURCES=[
 {source:'AXS · Toyota Center',url:'https://www.axs.com/venues/101329/toyota-center-houston-tickets',venue:'Toyota Center',address:'1510 Polk Street, Houston, TX 77002',area:'Downtown',zip:'77002'},
 {source:'AXS · 713 Music Hall',url:'https://www.axs.com/venues/129281/713-music-hall-houston-tickets',venue:'713 Music Hall',address:'401 Franklin Street, Houston, TX 77201',area:'Downtown',zip:'77201'},
 {source:'NRG Park',url:'https://www.nrgpark.com/events-tickets/',venue:'NRG Park',address:'1 NRG Pkwy, Houston, TX 77054',area:'Greater Houston',zip:'77054'}
];
const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;|&#038;/g,'&').replace(/&#8217;|&rsquo;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (compatible; WTM/2.2; +https://wtm-whats-the-move.vercel.app)','accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
function imageOf(x){if(!x)return'';if(typeof x==='string')return x;if(Array.isArray(x))return imageOf(x[0]);return x.url||x.src||''}
function walk(o,out,ctx){if(!o||typeof o!=='object')return;const title=o.eventName||o.name||o.title;const start=o.startDate||o.startTime||o.eventDate||o.dateTime;const url=o.url||o.eventUrl||o.primaryEventUrl;const img=imageOf(o.image||o.images||o.eventImageUrl);if(title&&start){const d=new Date(start);if(!Number.isNaN(d.getTime())&&d.getTime()>Date.now()-3600000){let endDate=null;if(o.endDate){const ed=new Date(o.endDate);if(!Number.isNaN(ed.getTime()))endDate=ed.toISOString()}out.push({id:`${ctx.source}:${url||title}:${d.toISOString()}`.replace(/\s+/g,'_').slice(0,220),title:strip(title),source:ctx.source,date:d.toISOString(),endDate,area:ctx.area,venue:ctx.venue,address:ctx.address,zip:ctx.zip,price:null,url:url?new URL(url,ctx.url).toString():ctx.url,description:strip(o.description||o.eventNotes||''),image:img?new URL(img,ctx.url).toString():'',lat:null,lng:null,sourceMode:'primary inventory'})}}for(const v of Object.values(o)){if(v&&typeof v==='object'){if(Array.isArray(v))v.forEach(x=>walk(x,out,ctx));else walk(v,out,ctx)}}}
function parseJson(html,ctx){const out=[];const re=/<script[^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){const txt=m[1].trim();if(!txt||(!txt.startsWith('{')&&!txt.startsWith('[')))continue;try{walk(JSON.parse(txt),out,ctx)}catch{}}return out}
function parseNrg(html,ctx){const out=[],seen=new Set(),re=/(\d{2}\/\d{2}\/\d{4})[\s\S]{0,1400}?<h[1-4][^>]*>([\s\S]*?)<\/h[1-4]>/gi;let m;while((m=re.exec(html))){const d=new Date(m[1]+' 12:00:00');const title=strip(m[2]);if(!title||Number.isNaN(d.getTime())||d.getTime()<Date.now()-86400000)continue;const k=title+'|'+m[1];if(seen.has(k))continue;seen.add(k);out.push({id:`NRG:${k}`.replace(/\s+/g,'_'),title,source:'NRG Park',date:d.toISOString(),endDate:null,area:'Greater Houston',venue:'NRG Park',address:'1 NRG Pkwy, Houston, TX 77054',zip:'77054',price:null,url:ctx.url,description:'Official NRG Park event listing.',image:'',lat:29.6847,lng:-95.4107,sourceMode:'official venue calendar'})}return out}
function dedupe(list){const s=new Set();return list.filter(e=>{const k=(e.title+'|'+e.date+'|'+e.venue).toLowerCase();if(s.has(k))return false;s.add(k);return true})}
async function sourceResult(ctx){try{const html=await get(ctx.url);let events=parseJson(html,ctx);if(ctx.source==='NRG Park')events=events.concat(parseNrg(html,ctx));events=dedupe(events);return{source:ctx.source,url:ctx.url,mode:'primary inventory / official venue',status:events.length?'live':'no-readable-events',count:events.length,events}}catch(e){return{source:ctx.source,url:ctx.url,mode:'primary inventory / official venue',status:'unavailable',count:0,error:String(e.message||e),events:[]}}}
async function astros(){const source='Houston Astros',url='https://statsapi.mlb.com/api/v1/schedule';try{const start=new Date(),end=new Date();end.setDate(end.getDate()+150);const u=new URL(url);u.searchParams.set('sportId','1');u.searchParams.set('teamId','117');u.searchParams.set('startDate',start.toISOString().slice(0,10));u.searchParams.set('endDate',end.toISOString().slice(0,10));u.searchParams.set('hydrate','venue');const r=await fetch(u,{headers:{'user-agent':'WTM/2.2'}});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json(),events=[];for(const day of j.dates||[])for(const g of day.games||[]){if(g.teams?.home?.team?.id!==117)continue;const opp=g.teams?.away?.team?.name||'Opponent',venue=g.venue?.name||'Daikin Park';events.push({id:'Astros:'+g.gamePk,title:`Houston Astros vs ${opp.replace(/^Houston Astros$/,'')}`.replace(/vs\s*$/,'').trim(),source,date:new Date(g.gameDate).toISOString(),endDate:null,area:'Downtown',venue,address:'501 Crawford St, Houston, TX 77002',zip:'77002',price:null,url:`https://www.mlb.com/astros/schedule`,description:`Houston Astros home game at ${venue}.`,image:'',lat:29.7573,lng:-95.3555,sourceMode:'official league schedule'})}return{source,url:'https://www.mlb.com/astros/schedule',mode:'official MLB schedule',status:events.length?'live':'no-upcoming-home-games',count:events.length,events}}catch(e){return{source,url:'https://www.mlb.com/astros/schedule',mode:'official MLB schedule',status:'unavailable',count:0,error:String(e.message||e),events:[]}}}
async function ticketmaster(){const key=process.env.TICKETMASTER_API_KEY;if(!key)return{source:'Ticketmaster',url:'https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/',mode:'official Discovery API',status:'api-key-needed',count:0,events:[]};try{const u=new URL('https://app.ticketmaster.com/discovery/v2/events.json');u.searchParams.set('apikey',key);u.searchParams.set('countryCode','US');u.searchParams.set('geoPoint','9vk1');u.searchParams.set('radius','70');u.searchParams.set('unit','miles');u.searchParams.set('size','200');u.searchParams.set('sort','date,asc');const r=await fetch(u);if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();const raw=j?._embedded?.events||[];const events=raw.map(x=>{const v=x._embedded?.venues?.[0]||{},a=v.address||{},city=v.city?.name||'',state=v.state?.stateCode||'',zip=v.postalCode||'',img=(x.images||[]).sort((a,b)=>(b.width||0)-(a.width||0))[0]?.url||'',price=x.priceRanges?.[0]?.min??null,cls=x.classifications?.[0],start=x.dates?.start?.dateTime||x.dates?.start?.localDate;return{id:'Ticketmaster:'+x.id,title:x.name,source:'Ticketmaster',date:new Date(start).toISOString(),endDate:null,area:city&&city!=='Houston'?city:'Greater Houston',venue:v.name||'Houston area',address:[a.line1,city,state,zip].filter(Boolean).join(', '),zip,price,url:x.url,description:[x.info,x.pleaseNote,cls?.segment?.name,cls?.genre?.name].filter(Boolean).join(' · '),image:img,lat:Number(v.location?.latitude)||null,lng:Number(v.location?.longitude)||null,sourceMode:'official API'}});return{source:'Ticketmaster',url:'https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/',mode:'official Discovery API',status:'live',count:events.length,events}}catch(e){return{source:'Ticketmaster',url:'https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/',mode:'official Discovery API',status:'error',count:0,error:String(e.message||e),events:[]}}}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','s-maxage=600, stale-while-revalidate=1800');const results=await Promise.all([...SOURCES.map(sourceResult),astros(),ticketmaster()]);const events=dedupe(results.flatMap(r=>r.events||[])).sort((a,b)=>new Date(a.date)-new Date(b.date));res.json({generatedAt:new Date().toISOString(),events,statuses:results.map(({events,...x})=>x)})};